scraper:
  headless: New
  user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
  timeout_seconds: 230

urls: 
  sociedades: https://www.registrodeempresasysociedades.cl/Busqueda/ActuacionDetalle.aspx?TipoBusqueda=4&ParamBusqueda1=
  diario_oficial: https://www.diariooficial.interior.gob.cl/edicionelectronica/index.php?date=
  
output:
  sociedades: /tmp/empresa_scraper.jsonl 
  diario_oficial: /tmp/diario_scraper.jsonl
  log_file: /tmp/failed_uploads.csv
  json_output_folder: /tmp/output

aws:
  s3_bucket: 'v1-st-bech-inegocio-analitica-sandbox-zone'
  s3_name: 'scraper/fiscalia'
  region: 'us-east-1'
  

email:
  to: ['facu_mt@hotmail.com']
  from: "ftoneguz@bancoestado.cl"
  subject: "Reporte: Modificación de sociedades"
  body: "Reporte Modificación de Sociedades, incluye información de /n del diario oficial  y de registro de empresas y sociedades"
  file_name: "Modificacion_sociedades"

columns:
  all: ['fuente','rut','rut_df','razon_social', 'url', 'actuacion', 'nro_atencion', 'cve',
    'segmento', 'plataforma', 'ejec_cod', 'rut_funcionario', 'rut_funcionario_dv',
    'nombre_funcionario', 'nombre_puesto', 'correo', 'dependencia',
    'pa_date', 'fecha_actuacion']
  
  delivery: ['fuente','rut','rut_df','razon_social', 'url', 'actuacion', 'nro_atencion', 'cve',
            'segmento', 'plataforma', 'ejec_cod','nombre_funcionario', 'nombre_puesto', 
            'correo', 'dependencia','fecha_actuacion']
