scraper:
  headless: New
  user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
  timeout_seconds: 10

urls: 
  url_1: https://www.registrodeempresasysociedades.cl/Busqueda/ActuacionDetalle.aspx?TipoBusqueda=4&ParamBusqueda1=
  url_2: https://otra-pagina.cl
  
output:
  log_file: logs/failed_uploads.csv
  json_output_folder: data/output

