scraper:
  headless: New
  user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
  timeout_seconds: 230

urls: 
  sociedades: https://www.registrodeempresasysociedades.cl/Busqueda/ActuacionDetalle.aspx?TipoBusqueda=4&ParamBusqueda1=
  diario_oficial: https://www.diariooficial.interior.gob.cl/edicionelectronica/index.php?date=
  
output:
  sociedades: /tmp/empresa_scraper.jsonl 
  diario_oficial: /tmp/diario_scraper.jsonl
  log_file: /tmp/failed_uploads.csv
  json_output_folder: /tmp/output

aws:
  s3_bucket: 'v1-st-bech-inegocio-analitica-sandbox-zone'
  s3_name: 'scraper/fiscalia'
  region: 'us-east-1'
  athena_maestro_empresa: ''